Repository pika-2023/saeroksaerok-frontend, pull requests merged in 2023-05, with the labels that each got.

#1 [all/media query] 반응형 세팅
  pwa/package.json
  pwa/public/images/web_phone.webp
  pwa/public/index.html
  pwa/src/index.js
  pwa/src/pages/Splash/Splash.js
  pwa/src/shared/Device.js
  pwa/src/styles/AppLayout.js
Labels: 리뷰 요청, 스타일링

#2 :adhesive_bandage: 자잘한 오류 수정
  pwa/public/manifest.json
  pwa/src/shared/Device.js
Labels: 리팩토링

#3 [all / init] 전체 화면 스크롤 활성화
  pwa/package-lock.json
  pwa/package.json
  pwa/public/images/KakaoTalk_Photo_2023-05-23-13-26-47 003.jpeg
  pwa/public/index.html
  pwa/src/Router.js
  pwa/src/index.js
  pwa/src/shared/Device.js
  pwa/src/state/Sample.js
  pwa/src/state/store.js
  pwa/src/styles/AppLayout.js
  pwa/src/styles/GlobalStyle.js
  pwa/src/styles/theme.js
  pwa/src/styles/variables.js
Labels: 에러 해결, 리뷰 요청, 스타일링

#5 [layout / word] Word 메인 와이어프레임 및 모달 구현
  pwa/package-lock.json
  pwa/src/Router.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.js
  pwa/src/pages/Word/Word.js
  pwa/src/pages/Word/Word.style.js
Labels: 스타일링, 리뷰 완료

#6 [layout/voice-record] VoiceRecord 와이어프레임 구현
  pwa/src/Router.js
  pwa/src/assets/images/listeningIcon.png
  pwa/src/pages/Word/Result/Result.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.style.js
Labels: 스타일링, 리뷰 완료

#7 [layout/feed] 목데이터로 UI그리기 구현
  pwa/package-lock.json
  pwa/package.json
  pwa/public/data/friendsFeedData.json
  pwa/public/data/myFeedData.json
  pwa/src/Router.js
  pwa/src/pages/Feed/Feed.js
  pwa/src/pages/Feed/FeedDetail.js
  pwa/src/shared/Device.js
  pwa/src/state/store.js
Labels: 리뷰 요청, 스타일링

#8 [layout / result] Result 와이어프레임 구현
  pwa/src/pages/Word/Result/Result.js
Labels: 리뷰 완료

#9 [layout / word] Modal 컴포넌트 분리
  pwa/src/components/Modal.js
  pwa/src/pages/Word/Word.js
  pwa/src/pages/Word/Word.style.js
Labels: 리뷰 완료

#10 [layout / login] Login 와이어프레임 구현
  pwa/public/icons/favicon.ico
  pwa/public/icons/profileImgIcon.png
  pwa/src/pages/Account/Login.js
Labels: 스타일링, 리뷰 완료

#11 [layout / signup] Signup 와이어프레임 구현
  pwa/src/pages/Account/Signup.js
Labels: 스타일링, 리뷰 완료

#13 [layout / word] Word, VoiceRecord, Modal 리팩토링
  pwa/package-lock.json
  pwa/src/components/Modal.js
  pwa/src/components/Modal/Modal.js
  pwa/src/components/Modal/Modal.style.js
  pwa/src/components/Modal/modalData.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.js
  pwa/src/pages/Word/VoiceRecord/voiceRecordData.js
  pwa/src/pages/Word/Word.js
  pwa/src/pages/Word/Word.style.js
  pwa/src/state/store.js
Labels: 리팩토링, 리뷰 완료

#12 [layout / feed] Feed 페이지 css 수정
  pwa/src/pages/Feed/Feed.js
Labels: 스타일링, 리뷰 완료

#14 [layout / feed-detail] FeedDetail page UI 1차 완성 및 댓글 남기기 모달 생성
  pwa/public/data/friendsFeedData.json
  pwa/public/data/myFeedData.json
  pwa/src/components/CommentModal.js
  pwa/src/components/CommentType.js
  pwa/src/pages/Feed/Feed.js
  pwa/src/pages/Feed/FeedDetail.js
  pwa/src/state/store.js
Labels: 스타일링, 리뷰 완료
