Repository pika-2023/saeroksaerok-frontend, pull requests merged in 2023-06, with the labels that each got.

#17 [layout / init] 디자인 시스템 초기세팅 (⚡️머지 우선순위 높음)
  pwa/package-lock.json
  pwa/public/icons/icon_feed_off.png
  pwa/public/icons/icon_feed_on.png
  pwa/public/icons/icon_keyboard.png
  pwa/public/icons/icon_reminisce_off.png
  pwa/public/icons/icon_reminisce_on.png
  pwa/public/icons/icon_voice.png
  pwa/public/icons/saeroksaerok_logo_512x512.png
  pwa/public/icons/saeroksaerok_logo_inapp.png
  pwa/public/icons/saeroksaerok_logotype.png
  pwa/public/icons/saeroksaerok_profile.png
  pwa/public/icons/saeroksaerok_symbolmark.png
  pwa/public/icons/text_family.png
  pwa/public/icons/text_friend.png
  pwa/public/icons/text_travel.png
  pwa/public/index.html
  pwa/src/components/CommentModal.js
  pwa/src/components/CommentType.js
  pwa/src/components/Modal/Modal.style.js
  pwa/src/index.js
  pwa/src/pages/Account/Login.js
  pwa/src/pages/Account/Signup.js
  pwa/src/pages/Feed/Feed.js
  pwa/src/pages/Feed/FeedDetail.js
  pwa/src/pages/Word/Result/Result.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.style.js
  pwa/src/pages/Word/Word.style.js
  pwa/src/shared/Device.js
  pwa/src/styles/GlobalStyle.js
  pwa/src/styles/fontStyle.js
  pwa/src/styles/fonts/MBC1961GulimOTFM.otf
  pwa/src/styles/theme.js
Labels: 스타일링, 추가 구현 진행중

#22 [layout/init] 이미지 업데이트
  pwa/public/images/bg_reminisce_after.png
  pwa/public/images/bg_reminisce_before.png
  pwa/public/images/icon_feed_off_2.png
  pwa/public/images/icon_feed_on_2.png
  pwa/public/images/icon_reminisce_off_2.png
  pwa/public/images/icon_reminisce_on_2.png
  pwa/public/images/saeroksaerok_logo_inapp.png
  pwa/public/images/saeroksaerok_logo_inapp_2.png
  pwa/public/images/saeroksaerok_logotype.png
  pwa/public/images/saeroksaerok_logotype_2.png
  pwa/public/images/saeroksaerok_symbolmark.png
  pwa/public/images/saeroksaerok_symbolmark_2.png
Labels: 기타, 리뷰 요청

#19 [layout / feed-detail] 키보드로 댓글달기 모달창 추가
  pwa/src/components/CommentType.js
Labels: 리뷰 요청, 스타일링

#25 🎨 icon.png 파일 위치 수정
  pwa/public/icons/icon_feed_off.png
  pwa/public/icons/icon_feed_off_2.png
  pwa/public/icons/icon_feed_on.png
  pwa/public/icons/icon_feed_on_2.png
  pwa/public/icons/icon_reminisce_off.png
  pwa/public/icons/icon_reminisce_off_2.png
  pwa/public/icons/icon_reminisce_on.png
  pwa/public/icons/icon_reminisce_on_2.png
Labels: 기타, 리뷰 요청

#24 [function/login] login 기능 구현 중
  pwa/src/pages/Account/Login.js
Labels: 기능 구현, 리뷰 요청

#23 [function/singup] 회원가입 및 프로필사진 업로드 기능 구현
  pwa/src/pages/Account/Signup.js
Labels: 기능 구현, 리뷰 요청

#29 [layout / init] 변경된 배경 이미지 파일 추가
  pwa/public/images/bg_ai_image.png
  pwa/public/images/bg_reminisce.png
  pwa/public/images/bg_reminisce_home.png
  pwa/public/images/bg_speach_to_text.png
  pwa/public/images/bg_splash.png
Labels: 기타, 스타일링

#30 [layout / login] Login 레이아웃 완성
  pwa/src/pages/Account/Login.js
  pwa/src/pages/Account/Signup.js
Labels: 스타일링, 리뷰 완료

#31 [layout / signup] Signup 레이아웃 완성
  pwa/src/pages/Account/Signup.js
Labels: 스타일링, 리뷰 완료

#18 [layout / word] Word 페이지 스타일 적용
  pwa/public/icons/icon_feed_off.png
  pwa/public/icons/icon_feed_on.png
  pwa/public/icons/icon_reminisce_off.png
  pwa/public/icons/icon_reminisce_on.png
  pwa/public/icons/saeroksaerok_logo_512x512.png
  pwa/public/icons/saeroksaerok_logo_inapp.png
  pwa/public/icons/saeroksaerok_logotype.png
  pwa/public/icons/saeroksaerok_profile.png
  pwa/public/icons/saeroksaerok_symbolmark.png
  pwa/public/icons/text_family.png
  pwa/public/icons/text_friend.png
  pwa/public/icons/text_travel.png
  pwa/src/components/Modal/Modal.js
  pwa/src/components/Modal/Modal.style.js
  pwa/src/components/Modal/modalData.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.style.js
  pwa/src/pages/Word/Word.js
  pwa/src/pages/Word/Word.style.js
Labels: 리뷰 완료

#32 [layout / result] Result 레이아웃 완성
  pwa/src/pages/Word/Result/Result.js
Labels: 스타일링, 리뷰 완료

#34 [layout/init] 덕담 관련 이미지파일 추가
  pwa/public/icons/icon_blessing_beautiful.png
  pwa/public/icons/icon_blessing_happy.png
  pwa/public/images/card_blessing_beautiful.png
  pwa/public/images/card_blessing_happy.png
Labels: 스타일링, 리뷰 완료

#16 [function / voice-record] VoiceRecord 음성 녹음 기능 구현
  pwa/package-lock.json
  pwa/package.json
  pwa/src/Router.js
  pwa/src/pages/Word/PictureResult/PictureResult.js
  pwa/src/pages/Word/Result/Result.js
  pwa/src/pages/Word/TextResult/TextResult.js
  pwa/src/pages/Word/VoiceRecord/RcFirst.js
  pwa/src/pages/Word/VoiceRecord/RcSecond.js
  pwa/src/pages/Word/VoiceRecord/RcThird.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.style.js
  pwa/src/pages/Word/Word.js
  pwa/src/state/store.js
Labels: 기능 구현, 에러 해결, 리뷰 완료

#28 [layout / feed] 액세스토큰을 이용한 통신 구현
  pwa/public/images/friend_memory.png
  pwa/public/images/my_memory.png
  pwa/src/pages/Feed/Feed.js
  pwa/src/pages/Feed/FeedDetail.js
Labels: 스타일링, 리뷰 완료

#36 [layout / voice-record] PictureResult 디자인 적용
  pwa/src/pages/Word/PictureResult/PictureResult.js
  pwa/src/pages/Word/VoiceRecord/RcFirst.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.style.js
Labels: 리뷰 완료

#37 [layout / result] TextResult 레이아웃 완성
  pwa/src/pages/Word/TextResult/TextResult.js
Labels: 스타일링, 리뷰 완료

#38 [layout / voice record] 전체 애니메이션 구현
  pwa/src/pages/Word/VoiceRecord/RcFirst.js
  pwa/src/pages/Word/VoiceRecord/RcSecond.js
  pwa/src/pages/Word/VoiceRecord/RcThird.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.style.js
  pwa/src/styles/animations.js
Labels: 스타일링, 리뷰 완료

#41 [function / result] 피드 공유하기 기능 구현, 라우터 수정, Signup 버튼 추가
  pwa/src/Router.js
  pwa/src/pages/Account/Signup.js
  pwa/src/pages/Word/PictureResult/PictureResult.js
Labels: 기능 구현, 에러 해결중

#40 [layout / resut] 추억 수정하기 모달 구현, 모달 템플릿화
  pwa/src/components/CommentModal.js
  pwa/src/components/Modal/Modal.js
  pwa/src/components/Modal/modalData.js
  pwa/src/pages/Feed/FeedDetail.js
  pwa/src/pages/Word/TextResult/TextResult.js
  pwa/src/state/store.js
Labels: 기능 구현, 스타일링, 추가 구현 진행중

#42 [layout / init] 디자인 수정사항 반영
  pwa/public/images/animation_loading.gif
  pwa/public/images/bg_reminisce_final.png
  pwa/public/images/bg_reminisce_final_flipped.png
  pwa/public/images/saeroksaerok_frame.png
  pwa/src/components/CommentModal.js
  pwa/src/components/CommentType.js
  pwa/src/components/Loading/Loading.js
  pwa/src/components/Modal/Modal.style.js
  pwa/src/components/Recall/Recall.js
  pwa/src/components/Splash/Splash.js
  pwa/src/pages/Account/Signup.js
  pwa/src/pages/Splash/Splash.js
  pwa/src/pages/Word/TextResult/TextResult.js
  pwa/src/pages/Word/VoiceRecord/RcFirst.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.style.js
  pwa/src/pages/Word/Word.js
  pwa/src/pages/Word/Word.style.js
  pwa/src/state/store.js
  pwa/src/styles/animations.js
Labels: 리뷰 요청, 스타일링

#33 [layout/feed-detail] 와이어프레임 수정에 따른 UI 수정 중
  pwa/src/components/CommentModal.js
  pwa/src/components/CommentType.js
  pwa/src/pages/Feed/Feed.js
  pwa/src/pages/Feed/FeedDetail.js
Labels: 에러 해결, 리뷰 요청, 스타일링

#43 [layout / voice-record] VoiceRecord 애니메이션 완성
  pwa/src/Router.js
  pwa/src/components/CommentModal.js
  pwa/src/components/Modal/Modal.js
  pwa/src/components/Recall/Recall.js
  pwa/src/pages/Account/Signup.js
  pwa/src/pages/Word/TextResult/TextResult.js
  pwa/src/pages/Word/VoiceRecord/RcFirst.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.js
Labels: 리팩토링, 리뷰 요청, 스타일링

#46 [function / refactoring] 전체 리팩토링
  pwa/public/data/friendsFeedData.json
  pwa/public/data/myFeedData.json
  pwa/src/Router.js
  pwa/src/components/CommentModal.js
  pwa/src/components/CommentType.js
  pwa/src/components/Loading/Loading.js
  pwa/src/components/Modal/Modal.js
  pwa/src/components/Modal/Modal.style.js
  pwa/src/components/Recording/RcFirst.js
  pwa/src/components/Recording/RcSecond.js
  pwa/src/components/Recording/RcThird.js
  pwa/src/pages/Account/Account.style.js
  pwa/src/pages/Account/Login.js
  pwa/src/pages/Account/Signup.js
  pwa/src/pages/Feed/Feed.js
  pwa/src/pages/Feed/Feed.style.js
  pwa/src/pages/Feed/FeedDetail.js
  pwa/src/pages/Feed/FeedDetail/FeedDetail.js
  pwa/src/pages/Feed/FeedDetail/FeedDetail.style.js
  pwa/src/pages/Word/PictureResult/PictureResult.js
  pwa/src/pages/Word/PictureResult/PictureResult.style.js
  pwa/src/pages/Word/TextResult/TextResult.js
  pwa/src/pages/Word/TextResult/TextResult.style.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.js
  pwa/src/pages/Word/VoiceRecord/VoiceRecord.style.js
  pwa/src/pages/Word/Word.js
  pwa/src/pages/Word/Word.style.js
  pwa/src/state/Sample.js
  pwa/src/state/store.js
  pwa/src/styles/GlobalStyle.js
  pwa/src/styles/fonts/MBC1961GulimOTFM.otf
Labels: 리팩토링
